# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flicks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'ACProgressHUD-Swift', '~> 1.2' 
  # Pods for Flicks

  target 'FlicksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlicksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
